-- Supabase table definitions for Gurnam Farms

create table if not exists newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists harvest_reservations (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  city text not null,
  notes text,
  created_at timestamptz not null default now()
);
